pyMANGA as pip package:
pymanga/pyMANGA pull request #109
Opened 2021-08-26 20:03 UTC by jvollhueter

- 260821
- first commit

2021-08-31 07:21 UTC, jbathmann requested changes
Some open questions in the comments... Otherwise thanks a lot!

2021-08-31 07:21 UTC, jbathmann commented on MANGA.py
>  from TimeLoopLib import TreeDynamicTimeStepping
I can only review this after merge of #99 and rebase

2021-08-31 07:21 UTC, jbathmann commented on PopulationLib/GroupPlanting.py
> +from pyMANGA.PopulationLib.TreeGroup import TreeGroup
PLib is not required?

2021-08-31 07:21 UTC, jbathmann commented on TreeModelLib/BelowgroundCompetition/SimpleTest/__init__.py
> +from pyMANGA.TreeModelLib.BelowgroundCompetition.SimpleTest.SimpleTest import SimpleTest
Ok... I get the idea. When does this work know? Do I have to install MANGA via pip or can I - for development purposes - just append the path to the source code?

Imagine I got both i) the souce code and ii) the pip version. How to I define which version is used, if I type "import pyMANGA" somewhere on my system? Can you add a short explanation file for this?

2021-08-31 07:32 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/SimpleTest/__init__.py
> +from pyMANGA.TreeModelLib.BelowgroundCompetition.SimpleTest.SimpleTest import SimpleTest
This is a problem at the moment. If pyManga is installed it uses the package and not the development source code....

2023-07-29 17:10 UTC, mcwimm commented
outdated

2023-07-29 17:10 UTC, closed without merging