add script for ogs grid
pymanga/pyMANGA pull request #212
Opened 2023-01-19 16:37 UTC by jvollhueter

In this PR is a script added with which you can create a grid out of given (geometric) parameters

2023-01-20 12:12 UTC, jvollhueter commented
Please don't merge, script does not work

2023-01-20 12:22 UTC, jvollhueter commented
works

2023-01-23 12:59 UTC, jbathmann commented on Benchmarks/ExampleSetups/OGSExampleSetup/MakeGrid.py
> +                                       "top_boundary.vtu -x 0 -y 0 -z -1 -a 30.")
This part only runs with windows systems. In the docs, a description for ubuntu files can be found. Can you maybe add a check for the operating system in order to decide which part to use? Example can be found in OGSLargeScale3D.py

2023-01-23 12:59 UTC, jbathmann requested changes
See comment

2023-02-09 17:33 UTC, jvollhueter commented
Now the script works with Windows and Linux based os. MacOS-User have to adopt it manually.

2023-02-10 14:49 UTC, jbathmann approved these changes
Looks good!

2023-02-14 10:09 UTC, jbathmann commented
Any reason to wait with the merge?

2023-02-14 10:11 UTC, jvollhueter commented
> Any reason to wait with the merge?

I don't think so. Should I merge it?

2023-02-14 12:34 UTC, merged