Wording
pymanga/pyMANGA pull request #236
Opened 2023-05-16 09:47 UTC by mcwimm

- mainly "tree" to "plant"

DO NOT MERGE BEFORE ALL BENCHMARKS ARE RUNNING

2023-05-26 10:41 UTC, jvollhueter requested changes

2023-05-26 10:41 UTC, jvollhueter commented on ModelOutputLib/OnePlantOneFile/__init__.py
> +from .OnePlantOneFile import OneTreeOneFile
from .OnePlantOneFile import One**Plant**OneFile

2023-06-07 09:13 UTC, mcwimm commented on ModelOutputLib/OnePlantOneFile/__init__.py
> +from .OnePlantOneFile import OneTreeOneFile
changes

2023-06-09 14:08 UTC, jvollhueter approved these changes
Looks good. All tests were successful. Ready for merge

2023-06-09 15:33 UTC, merged