New structure 2growth
pymanga/pyMANGA pull request #240
Opened 2023-06-05 11:21 UTC by jvollhueter

New structure allows the use of more than one growth model

2023-06-07 08:14 UTC, mcwimm requested changes
Cool! It seems to work. 
I rebased this branch onto the master and made a change to GroupPlanting.py. I think, this script can be shortened in general.
Also I added some working examples in Benchmark/Examples (didn't see your temp folder before).
However, it quite difficult to see the actual changes. That's why I would suggest to do the following steps before approval:

- [ ] finish and merge PR #236 
- [ ] update benchmark files to run all tests (at least PlantModules/Bettina and TreeOutput)

2023-06-07 08:14 UTC, mcwimm commented on ProjectLib/Project.py
> +        # self.iniPlantDynamicConcept()
remove if not needed anymore

2023-06-07 08:14 UTC, mcwimm commented on ProjectLib/XMLtoProject.py
> +        # self.addPlantDynamicConcept()
remove if not needed anymore

2023-06-07 08:14 UTC, mcwimm commented on TimeLoopLib/DynamicTimeStep.py
> +        # self.plant_dynamic_concept = project.getPlantDynamicConcept()
remove if not needed

2023-06-07 08:14 UTC, mcwimm commented on TreeModelLib/BelowgroundCompetition/OGS/bin/AddElementQuality.exe
all this OGS files need to be removed... maybe drop this commit?

2023-06-14 15:47 UTC, jvollhueter commented
At the moment the initialization of the mortality concept does not work anymore.

2023-09-07 14:03 UTC, jvollhueter commented
@jvollhueter  argument time does not anymore get passed

2023-09-09 13:32 UTC, mcwimm approved these changes

2023-09-12 15:51 UTC, mcwimm commented
the reference files for the benchmark are missing. sorry I recently added *.csv to gitignore to avoid uploading model outputs....

2023-09-12 16:06 UTC, jvollhueter commented
Benchmark should now be completely included. xml tags are not allowed starting with a number, so had to change the structure a little bit. All .csv and .xml files are included now.

2023-09-12 16:54 UTC, jvollhueter commented
> > Benchmark should now be completely included. xml tags are not allowed starting with a number, so had to change the structure a little bit. All .csv and .xml files are included now.
> 
> 👍 perfect

So we can merge it?

2023-09-12 17:10 UTC, merged