Seed dispersal
pymanga/pyMANGA pull request #256
Opened 2023-06-29 08:14 UTC by ChrisWudel

Hallo,
Ich habe begonnen, die Samenausbreitung umzustrukturieren, indem ich die Fälle Random und FromFile in eine Klasse umgewandelt habe. Der Test mit "py .\MANGA.py -i .\Benchmarks\ModuleBenchmarks\PlantModules\Bettina\Belowground\FixedSalinity\FixedSalinity_CI.xml. 
"hat bereits im Fall Random funktioniert. Im FromFile Fall gibt es den Fehler, dass es kein max_id Attribut gibt, aber anscheinend wird es in PlantGroup in der addPlant Funktion benötigt.

Könnt ihr mir da weiterhelfen?
VG

2023-06-30 08:10 UTC, mcwimm requested changes
Cool! Ich habe dir Kommentare am Code gelassen. Es bedarf nur einer kleinen Änderung...

2023-06-30 08:10 UTC, mcwimm commented on PopulationLib/Dispersal/FromFile.py
> +    def recruitPlants(self):
Da das exakt der gleiche Code ist wie bei Random, wäre es hier sinnvoll diesen zu nutzen anstatt nochmal das gleiche zu schreiben (DRY Prinzip - don't repeat yourself).
Das geht z.B. gut umzusetzen mit Vererbung oder Komposition. Für beides findest du Beispiele in pyMANGA. Auf den ersten Blick würde ich aber letzteres empfehlen.

2023-06-30 08:10 UTC, mcwimm commented on PopulationLib/GroupPlanting.py
> +            self.dispersal.plantPlantsFromFile(args=distribution)
Wenn die Funktionen, die für das gleiche zuständig sind auch in jeder Klasse gleich heißen, kannst du hier auch etwas Code einsparen.

2023-06-30 08:10 UTC, mcwimm commented on PopulationLib/GroupPlanting.py
> +            print("<<<<<<<", self.dispersal.initializePopulation)
Bestenfalls keine prints commiten.

2023-07-10 06:43 UTC, ChrisWudel commented on PopulationLib/Dispersal/FromFile.py
> +    def plantPlantsFromFile(self, args):
Ja, das ist richtig, ich habe den Namen geändert.

2023-07-10 07:25 UTC, ChrisWudel commented on PopulationLib/Dispersal/FromFile.py
> +                self.addPlant(x, y, initial_geometry=geometry)
mh... Hier sehe ich die Analogie zu Random leider nicht. Meinst du diesen Abschnitt?  
        x_i, y_i = [], []
        for i in range(n_individuals):
            r_x, r_y = (np.random.rand(2))
            x_i.append(self.x_1 + self.l_x * r_x)
            y_i.append(self.y_1 + self.l_y * r_y)
        self.x_i = x_i
        self.y_i = y_i

2023-07-11 06:40 UTC, mcwimm commented on PopulationLib/Dispersal/FromFile.py
> +                self.addPlant(x, y, initial_geometry=geometry)
Es geht um die Funktion `addPlant`. Die musste bei Random auch verschoben werden.

2023-08-31 11:38 UTC, mcwimm commented
Die Bsp.Datei bringt folgende Meldung: 'INFO: MANGA execution stopped because all plants died and no new plant were recruited.'
Also anscheinend gibt es keine Bäume. Das Modell geht nicht mal in den ersten Zeitschritt.

2023-10-25 08:54 UTC, mcwimm commented
addressed in new PR #290

2023-10-25 08:54 UTC, closed without merging