Introduce cases for fixedsalinity
pymanga/pyMANGA pull request #271
Opened 2023-08-04 11:45 UTC by mcwimm

@jvollhueter @zaphod-bx 
based on our discussion this week, I added "cases" to the fixed salinity modules. Would this fit your requirements?

2023-08-15 07:57 UTC, zaphod-bx requested changes

2023-08-15 07:57 UTC, zaphod-bx commented on ResourceLib/BelowGround/Individual/FixedSalinity/FixedSalinity.md
it is not an "exponential" function. I would suggest "sigmoidal salinity stress factor" ?

2023-08-15 07:57 UTC, zaphod-bx commented on ResourceLib/BelowGround/Individual/FixedSalinity/FixedSalinity.py
> +        if len(missing_tags) > 1:
works! But isn't there the danger, that variant is given, but anothere missing?

2023-08-15 08:01 UTC, zaphod-bx commented
I think it doesn't fit my requirements. At least I don't see how. I would need that the tree gets a variable "salinity" with a value of average salinity in the root zone for estimating the required vessel diameter distribution (in the tree - module).

2023-08-15 08:03 UTC, zaphod-bx commented on ResourceLib/BelowGround/Individual/FixedSalinity/FixedSalinity.py
> +            psi_sali = np.array(psi_zero) + 85000000 * salinity_plant
these 3 lines is what I have to reverse in the tree module to conclude back on "salinity_plant"

2023-08-16 09:12 UTC, mcwimm commented on ResourceLib/BelowGround/Individual/FixedSalinity/FixedSalinity.py
> +            psi_sali = np.array(psi_zero) + 85000000 * salinity_plant
So you need the salinity value to be transfered between modules? If so, the value can just be saved as other growth variables.

2023-08-23 09:15 UTC, mcwimm commented on ResourceLib/BelowGround/Individual/FixedSalinity/FixedSalinity.md
fixed

2023-08-23 09:33 UTC, mcwimm commented on ResourceLib/BelowGround/Individual/FixedSalinity/FixedSalinity.py
> +            psi_sali = np.array(psi_zero) + 85000000 * salinity_plant
Maybe it`s not a good idea to transfer salinity directly....

2023-08-23 09:58 UTC, jvollhueter approved these changes
ready to merge

2023-08-23 11:01 UTC, jvollhueter approved these changes
ready

2023-08-23 11:03 UTC, jvollhueter commented on ResourceLib/BelowGround/Individual/FixedSalinity/FixedSalinity.py
> +            psi_sali = np.array(psi_zero) + 85000000 * salinity_plant
.

2023-08-23 11:05 UTC, zaphod-bx approved these changes

2023-08-23 11:06 UTC, merged