saltmarsh model
pymanga/pyMANGA pull request #333
Opened 2024-03-15 18:46 UTC by jvollhueter

Adding saltmarsh model module

2024-03-20 15:47 UTC, mcwimm reviewed
The code looks good (except for the small things I commented). In general, more inline comments would be helpful.

2024-03-20 15:47 UTC, mcwimm commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +        self.sickly = False
Please change variable name. e.g. self.shrinking
+ it seems like the variable is not used elsewhere?

2024-03-20 15:47 UTC, mcwimm commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +    def prepareNextTimeStep(self, t_ini, t_end):
Only add documentation to inherited functions if anything changes compared to the parent method.

2024-03-20 15:47 UTC, mcwimm commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +        """
same as above

2024-03-20 15:47 UTC, mcwimm commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +    def progressPlant(self, plant, aboveground_factor, belowground_factor):
so far, all plant concepts take ..._resources.
Maybe do the same and we change it letter everywhere

2024-03-20 15:47 UTC, mcwimm commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +        Calculate the total plant volume.
Add shape of plant to doc

2024-03-20 15:47 UTC, mcwimm commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +        self.r_volum_ag_bg = volume_ag / volume_bg
``
```suggestion
        self.r_vol_ag_bg = volume_ag / volume_bg
```

2024-03-20 15:47 UTC, mcwimm commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +        if self.bg_factor != 0 or self.ag_factor != 0:
I'm a bit slow but does this mean if there are any resources do something?
If so, the following is maybe easier to read
`if (self.bg_factor + self.ag_factor) != 0:`

2024-03-20 15:47 UTC, mcwimm commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +            w_ratio_b_a = self.parameter['w_b_a'] * (1 + ratio_b_a_resource)
Not knowing the equations and there meaning it is quite difficult to distinguish between the weights itself and weighting parameters...

2024-03-20 15:47 UTC, mcwimm commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +            self.inc_h_bg = 0
Is this neccessary?

2024-04-16 12:47 UTC, jvollhueter commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +        self.sickly = False
Done

2024-04-16 13:26 UTC, jvollhueter commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +    def prepareNextTimeStep(self, t_ini, t_end):
Done

2024-04-16 13:33 UTC, jvollhueter commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +        """
Done

2024-04-16 13:38 UTC, jvollhueter commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +    def progressPlant(self, plant, aboveground_factor, belowground_factor):
No changes at this moment, problem mentioned in issue

2024-04-16 13:42 UTC, jvollhueter commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +        Calculate the total plant volume.
Done

2024-04-16 13:48 UTC, jvollhueter commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +                                   (self.bg_factor + self.ag_factor)) - 0.5) / 5
This leads to a normalization of -20 to +20 %

2024-04-16 13:51 UTC, jvollhueter commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +            self.inc_h_bg = 0
Maybe for automatic postprocessing, that you can read it out of outputfiles

2024-04-30 11:28 UTC, mcwimm reviewed
Ein paar Kleinigkeiten sollten noch angepasst werden, aber ansonsten passt es.

Gleichungen habe ich nicht geprüft, da ich nicht weiß was raus kommt. Aber Simulationsergebnis einer Pflanze sieht schlüssig aus, oder?
![image](https://github.com/pymanga/pyMANGA/assets/48250781/fa3b641a-7e40-4101-9583-344212b25408)

2024-04-30 11:28 UTC, mcwimm commented on Benchmarks/ModuleBenchmarks/PlantModules/Saltmarsh/Default/Default.xml
> +                <filename> Benchmarks/ModuleBenchmarks/PlantModules/Saltmarsh/input_OnePlant.csv </filename>
Die Datei fehlt noch online... 
Du kannst ja das Benchmark erstmal so anlegen wie bei Bettina. Da gibt es auch einmal alle Dateien für den Referenz-Baum.

2024-04-30 11:28 UTC, mcwimm commented on PlantModelLib/Mortality/Mortality.py
> +            elif case == "Threshold":
Gibt es andere Modelle, die so einen Mortalitätsansatz benutzen? Falls ja, hilft das vielleicht bei der Namesgebung.

2024-04-30 11:28 UTC, mcwimm commented on PlantModelLib/Mortality/Threshold/Threshold.md
> +The Memory mortality concept.
Bevor es falsch im Master landet, lieber Doc. leer lassen oder "coming soon" reinschreiben

2024-04-30 11:28 UTC, mcwimm commented on PlantModelLib/Mortality/Threshold/Threshold.py
> +        if self.threshold_type == "biovolume":
Soll das jetzt doch als absoluter Wert bleiben?

2024-04-30 11:28 UTC, mcwimm commented on PlantModelLib/Mortality/Threshold/Threshold.py
> +            print("Threshold: " + str(self.threshold))
prints entfernen

2024-04-30 11:28 UTC, mcwimm commented on PlantModelLib/Mortality/Threshold/__init__.py
> +.. include:: ./Memory.md
```suggestion
.. include:: ./Threshold.md
```

2024-04-30 11:28 UTC, mcwimm commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +
Du kannst gern Kommentare im Code verwenden. Hier zB "# Growth weights" (falls das stimmt)

2024-04-30 11:28 UTC, mcwimm commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +    def progressPlant(self, plant, aboveground_factor, belowground_factor):
Na doch. Du solltest es deshalb wie in allen plant modules nennen. Und später korrigieren wir das,,,

2024-04-30 11:28 UTC, mcwimm commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +
Leerzeile löschen

2024-04-30 11:28 UTC, mcwimm commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +                                   (self.bg_factor + self.ag_factor)) - 0.5) / 5
Dann vielleicht in Docstring oder Code Kommentar packen

2024-04-30 11:28 UTC, mcwimm commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +        Calculate the maintenance of the plant.
Can you add the unit to the doc

2024-05-21 12:01 UTC, jvollhueter commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +            w_ratio_b_a = self.parameter['w_b_a'] * (1 + ratio_b_a_resource)
I am still discussing with Britta about a meaningful naming of the variables in the ODD. I would wait for the result and then name the code according to the ODD - or can the variables also be named differently?

2024-05-21 12:04 UTC, jvollhueter commented on PlantModelLib/Mortality/Mortality.py
> +            elif case == "Threshold":
Somehow I can't find a good name here... Do you think that Threshold doesn't fit in general? Otherwise something like biomass threshold might be an idea...

2024-05-21 12:08 UTC, jvollhueter commented on PlantModelLib/Mortality/Threshold/Threshold.py
> +        if self.threshold_type == "biovolume":
Not in the long term, but for the time being it's enough for my applications. Should I expand it before merging, or can it go into the master as it is?

2024-05-22 10:56 UTC, mcwimm commented on PlantModelLib/Saltmarsh/Saltmarsh.py
> +            w_ratio_b_a = self.parameter['w_b_a'] * (1 + ratio_b_a_resource)
They should have the same names but with many of our modules that is not the case... so better wait for her approval

2024-05-22 10:57 UTC, mcwimm commented on PlantModelLib/Mortality/Threshold/Threshold.py
> +        if self.threshold_type == "biovolume":
No, it's fine

2024-05-22 11:12 UTC, mcwimm requested changes
Currently it's not running. I think because of the missing definition of the plant geometry in PopulationLib/Dispersal/FromFile/FromFile.py

2024-05-22 11:12 UTC, mcwimm commented on Benchmarks/ModuleBenchmarks/PlantModules/Saltmarsh/Default/Default.xml
It would be nice to have a complete benchmark, i.e., including reference files etc.

2024-05-24 14:37 UTC, mcwimm requested changes

2024-05-24 14:37 UTC, mcwimm commented on PlantModelLib/Mortality/Threshold/Threshold.py
> +    def __init__(self, args, case):
```suggestion
    def __init__(self, args):
```

2024-05-24 14:37 UTC, mcwimm commented on PlantModelLib/Mortality/Threshold/Threshold.py
> +        super().__init__(args, case)
```suggestion
        super().__init__(args)
```

2024-05-24 14:37 UTC, mcwimm commented on PlantModelLib/Mortality/Threshold/Threshold.py
> +            "optional": ["type", "mortality", "threshold", "threshold_type"]
All your parameters are optional inputs but not all have defined defaults.

2024-05-24 14:39 UTC, mcwimm commented on PlantModelLib/Mortality/Threshold/Threshold.py
> +
remove the line breaks between function name and body

2024-05-24 14:41 UTC, mcwimm commented
What is weird that the following variables are always NaN in the output file:
	ag_resources	bg_resources	inc_r_ag	inc_h_ag	inc_r_bg	inc_h_bg

2024-11-07 15:16 UTC, mcwimm commented
@jvollhueter ist der PR noch aktuell oder wurde der durch PR #360 abgelöst?

2024-11-07 20:00 UTC, jvollhueter commented
> @jvollhueter ist der PR noch aktuell oder wurde der durch PR #360 abgelöst?

Der ist veraltet, ich habe ihn nur vergessen zu löschen - mache ich gleich

2024-11-07 20:00 UTC, closed without merging